### ISSUE TITLE
Image frame issue.

### ISSUE THREAD

**Issue by Mitesh-Mewada** [PayalUmraliya/PUGifLoading#2]
Hey @PayalUmraliya its great tutorial and thanks for save my time, I face issue when change loading(gif) image that time showing loader image size is very small and i update "imageView" frame `imageView.frame = CGRect(x: 20.0, y: 50.0, width: 120, height: 120)` but its can't change how to solve this ?

**Comment by PayalUmraliya** [comment]
Hello it will work by changing image width and height. imageView.frame = CGRect(x: 20.0, y: 50.0, width: 120, height: 120)  i tried same and it is working. You need to manage text origin y after changing image height.

**Comment by Mitesh-Mewada** [comment]
Thanks it's  work .
